Public Class termino_politica
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            If Not IsPostBack Then
                Dim texto As New StringBuilder
                texto.Append("	                <body style=""background-color: inherit;"">	")
                texto.Append("	                <div style=""background-color: white;"">	")
                texto.Append("	                <h2>	")
                texto.Append("	                    ACUERDO SOBRE T&Eacute;RMINOS DE USO Y POL&Iacute;TICAS DE PRIVACIDAD	")
                texto.Append("	                </h2>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    El presente acuerdo contiene los t&eacute;rminos y condiciones generales, aplicables	")
                texto.Append("	                    al uso de los servicios ofrecidos por Carro Seguro Carseg S.A. (en adelante Carseg),	")
                texto.Append("	                    dentro de su sitio ... (en adelante el sitio).&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    Cualquier persona que desee acceder y/o usar el sitio o los servicios de &eacute;ste,	")
                texto.Append("	                    podr&aacute; hacerlo siempre que se sujete a los t&eacute;rminos y condiciones aqu&iacute;	")
                texto.Append("	                    contenidas, junto con las dem&aacute;s pol&iacute;ticas y principios que rigen el	")
                texto.Append("	                    sitio; por tanto, quien no acepte estos t&eacute;rminos y condiciones generales,	")
                texto.Append("	                    que tienen car&aacute;cter obligatorio y vinculante, deber&aacute; abstenerse de	")
                texto.Append("	                    utilizar el sitio y/o los servicios.</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    El Usuario debe leer, entender y aceptar todas las condiciones establecidas en el	")
                texto.Append("	                    presente instrumento, as&iacute; como en los dem&aacute;s documentos incorporados	")
                texto.Append("	                    por referencia, previa a su inscripci&oacute;n como usuario de Carseg.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    1. Los servicios de Carseg s&oacute;lo est&aacute;n disponibles para personas que	")
                texto.Append("	                    tengan capacidad legal para contratar; por tanto, no deben ser utilizados por menores	")
                texto.Append("	                    de edad, personas que no tengan esa capacidad o aquellas que hayan sido suspendidas	")
                texto.Append("	                    o dadas de baja del sistema de Carseg, temporal o definitivamente, por haber incumplido	")
                texto.Append("	                    las disposiciones del presente instrumento, o por haber incurrido a criterio de	")
                texto.Append("	                    Carseg, en conductas o actos dolosos o fraudulentos, mediante el uso del sitio o	")
                texto.Append("	                    de los servicios. Si usted est&aacute; inscribiendo un usuario como persona jur&iacute;dica,	")
                texto.Append("	                    debe tener capacidad para contratar a nombre de la misma, y de obligar a &eacute;sta	")
                texto.Append("	                    en los t&eacute;rminos de este acuerdo.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    2. El usuario se obliga a completar el formulario de inscripci&oacute;n en todos	")
                texto.Append("	                    sus campos, para poder utilizar los servicios que brinda Carseg El usuario se obliga	")
                texto.Append("	                    a consignar su informaci&oacute;n personal de manera exacta, precisa y verdadera,	")
                texto.Append("	                    y asume el compromiso de actualizar sus datos personales cuando sea necesario. Carseg	")
                texto.Append("	                    podr&aacute; utilizar diversos medios para identificar a sus usuarios, pero Carseg	")
                texto.Append("	                    no se responsabiliza por la certeza de los datos personales provistos por sus usuarios.	")
                texto.Append("	                    En consecuencia, los usuarios garantizan y responden, en cualquier caso, de la veracidad,	")
                texto.Append("	                    exactitud, vigencia y autenticidad de los datos personales ingresados.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    3. El usuario acceder&aacute; a su cuenta personal en el sitio, mediante el ingreso	")
                texto.Append("	                    de &hellip; y una clave de seguridad personal elegida por &eacute;ste. El usuario	")
                texto.Append("	                    se obliga a mantener la confidencialidad de su clave de seguridad. El usuario ser&aacute;	")
                texto.Append("	                    responsable por todas las operaciones efectuadas en su cuenta, pues el acceso a	")
                texto.Append("	                    la misma est&aacute; restringido al ingreso y uso de su clave de seguridad, de conocimiento	")
                texto.Append("	                    exclusivo del usuario. El usuario se compromete a notificar a Carseg, en forma inmediata	")
                texto.Append("	                    y por medio id&oacute;neo y fehaciente, cualquier uso no autorizado de su cuenta,	")
                texto.Append("	                    as&iacute; como el ingreso por terceros no autorizados a la misma.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    4. Carseg no vender&aacute;, alquilar&aacute; ni negociar&aacute; con otras empresas	")
                texto.Append("	                    los datos personales de sus usuarios, salvo su autorizaci&oacute;n en contrario.	")
                texto.Append("	                    Estos datos ser&aacute;n usados por Carseg, &uacute;nicamente para perfeccionar	")
                texto.Append("	                    la transacci&oacute;n. La informaci&oacute;n personal de los usuarios se procesa	")
                texto.Append("	                    y almacena en servidores o medios magn&eacute;ticos que mantienen altos est&aacute;ndares	")
                texto.Append("	                    de seguridad y protecci&oacute;n tanto f&iacute;sica como tecnol&oacute;gica.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    5. Carseg no se responsabiliza del entendimiento, interpretaci&oacute;n y/o uso	")
                texto.Append("	                    del contenido del sitio por parte de sus usuarios; por tanto, el uso de la informaci&oacute;n	")
                texto.Append("	                    es responsabilidad exclusiva del usuario. Carseg se reserva la facultad de modificar	")
                texto.Append("	                    el contenido y/o servicio por s&iacute; mismo o mediante un tercero autorizado,	")
                texto.Append("	                    sin que est&eacute; obligado a notificar previamente al usuario.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    6. Carseg no garantiza el acceso permanente e ininterrumpido al sitio, ni que el	")
                texto.Append("	                    servicio o servidor est&eacute; libre de virus. El usuario debe tomar las medidas	")
                texto.Append("	                    necesarias para evitar los efectos del mismo.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    7. No est&aacute; permitido el uso de ning&uacute;n dispositivo, software u otro	")
                texto.Append("	                    medio tendiente a interferir tanto en las actividades y operatividad del sitio de	")
                texto.Append("	                    Carseg, como en las ofertas o en las bases de datos de Carseg. Cualquier intromisi&oacute;n,	")
                texto.Append("	                    tentativa o actividad violatoria o contraria a las leyes sobre derecho de autor	")
                texto.Append("	                    y/o a las prohibiciones estipuladas en este documento, facultar&aacute;n a Carseg	")
                texto.Append("	                    el inicio de las acciones legales pertinentes; la imposici&oacute;n de las sanciones	")
                texto.Append("	                    previstas por este acuerdo; y, demandar una indemnizaci&oacute;n por los da&ntilde;os	")
                texto.Append("	                    y perjuicios irrogados.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    8. En cualquier momento Carseg podr&aacute; advertir, suspender o cancelar, temporal	")
                texto.Append("	                    o definitivamente la cuenta de un usuario o una transacci&oacute;n, e iniciar las	")
                texto.Append("	                    acciones que estime pertinentes, si se quebrantara alguna ley, o cualquiera de las	")
                texto.Append("	                    estipulaciones de este acuerdo, o si se incurriera a criterio de Carseg en conductas	")
                texto.Append("	                    o actos dolosos o fraudulentos, o, si no pudiera verificarse la identidad del usuario,	")
                texto.Append("	                    o cualquier informaci&oacute;n proporcionada por el mismo fuere err&oacute;nea.	")
                texto.Append("	                    En caso de suspensi&oacute;n o inhabilitaci&oacute;n de un usuario, todas las transacciones	")
                texto.Append("	                    u operaciones del usuario ser&aacute;n removidas del sistema.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    9. Carseg se reserva el derecho de cancelar la cuenta del usuario que hubiere incumplido	")
                texto.Append("	                    sus obligaciones derivadas de una transacci&oacute;n, o si se detectara en su conducta	")
                texto.Append("	                    intencionalidad de perjudicar o defraudar a otros usuarios.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    10. Carseg se reserva el derecho a cancelar una transacci&oacute;n por razones no	")
                texto.Append("	                    mencionadas anteriormente, o si considera que el usuario ha incurrido en alg&uacute;n	")
                texto.Append("	                    error involuntario, o por cualquier otra raz&oacute;n que Carseg considere justificada.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    11. Carseg emitir&aacute; el comprobante de venta a nombre de quien pag&oacute;.	")
                texto.Append("	                    El usuario/comprador tendr&aacute; la opci&oacute;n de indicar a nombre de qui&eacute;n	")
                texto.Append("	                    deber&aacute; emitirse el comprobante, si lo comunica con 24 horas de antelaci&oacute;n.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    12. Carseg podr&aacute; modificar en cualquier momento los t&eacute;rminos y condiciones	")
                texto.Append("	                    de este acuerdo, y notificar&aacute; los cambios al usuario, publicando una versi&oacute;n	")
                texto.Append("	                    actualizada de dichos t&eacute;rminos y condiciones en el sitio, con expresi&oacute;n	")
                texto.Append("	                    de la fecha de la &uacute;ltima modificaci&oacute;n. Dentro de los 5 d&iacute;as	")
                texto.Append("	                    siguientes a la publicaci&oacute;n de las modificaciones introducidas, el usuario	")
                texto.Append("	                    deber&aacute; comunicar por e-mail a &hellip;, si no acepta las mismas; en ese caso	")
                texto.Append("	                    quedar&aacute; disuelto el v&iacute;nculo contractual y ser&aacute; inhabilitado	")
                texto.Append("	                    como usuario. Vencido este plazo, se considerar&aacute; que el usuario acepta los	")
                texto.Append("	                    nuevos t&eacute;rminos y el acuerdo continuar&aacute; vinculando a ambas partes.&nbsp;</div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    <br />	")
                texto.Append("	                </div>	")
                texto.Append("	                <div style=""text-align: justify;"">	")
                texto.Append("	                    13. Se fija como domicilio de Carseg &hellip;, Guayaquil, Ecuador. En caso de dudas	")
                texto.Append("	                    sobre el presente acuerdo, y dem&aacute;s pol&iacute;ticas y principios que rigen	")
                texto.Append("	                    el sitio, puede contactarse a &hellip;</div>	")
                texto.Append("	                </div>	")
                texto.Append("	                </body>	")
                RadEditor1.Content = texto.ToString()
            End If
        Catch ex As Exception
            ExceptionHandler.Captura_Error(ex)
        End Try
    End Sub

End Class